using System;
using NUnit.Framework;
using UnityEngine;

namespace DataFerret.Analytics.Tests.EditMode
{
    [TestFixture]
    [Category("Core")]
    public class IdentityManagerTests
    {
        private const string AnonymousIdKey = "df_anonymous_id";
        private IdentityManager _identityManager;

        [SetUp]
        public void SetUp()
        {
            PlayerPrefs.DeleteKey(AnonymousIdKey);
            _identityManager = new IdentityManager();
        }

        [TearDown]
        public void TearDown()
        {
            PlayerPrefs.DeleteKey(AnonymousIdKey);
        }

        /// <summary>
        /// TC-IM-001: AnonymousId is auto-generated and is a valid GUID format.
        /// </summary>
        [Test]
        public void AnonymousId_WhenFirstAccessed_IsAutoGeneratedValidGuid()
        {
            var anonymousId = _identityManager.AnonymousId;

            Assert.That(anonymousId, Is.Not.Null.And.Not.Empty,
                "AnonymousId should not be null or empty");
            Assert.That(Guid.TryParse(anonymousId, out _), Is.True,
                "AnonymousId should be a valid GUID format");
        }

        /// <summary>
        /// TC-IM-002: AnonymousId is persisted in PlayerPrefs and can be read back.
        /// </summary>
        [Test]
        public void AnonymousId_WhenGenerated_IsPersistedInPlayerPrefs()
        {
            var anonymousId = _identityManager.AnonymousId;

            var storedValue = PlayerPrefs.GetString(AnonymousIdKey);
            Assert.That(storedValue, Is.EqualTo(anonymousId),
                "AnonymousId stored in PlayerPrefs should match the generated value");
        }

        /// <summary>
        /// TC-IM-003: SetUserId correctly sets the UserId value.
        /// </summary>
        [Test]
        public void SetUserId_WithValidId_SetsUserIdCorrectly()
        {
            const string expectedUserId = "user_12345";

            _identityManager.SetUserId(expectedUserId);

            Assert.That(_identityManager.UserId, Is.EqualTo(expectedUserId),
                "UserId should match the value passed to SetUserId");
        }

        /// <summary>
        /// TC-IM-004: Reset() clears userId (null) and generates a NEW anonymousId.
        /// </summary>
        [Test]
        public void Reset_WhenCalled_ClearsUserIdAndGeneratesNewAnonymousId()
        {
            _identityManager.SetUserId("user_12345");
            var originalAnonymousId = _identityManager.AnonymousId;

            _identityManager.Reset();

            Assert.That(_identityManager.UserId, Is.Null,
                "UserId should be null after Reset");
            Assert.That(_identityManager.AnonymousId, Is.Not.EqualTo(originalAnonymousId),
                "AnonymousId should be different after Reset");
            Assert.That(Guid.TryParse(_identityManager.AnonymousId, out _), Is.True,
                "New AnonymousId should still be a valid GUID");
        }

        /// <summary>
        /// TC-IM-005: UserId is null when not explicitly set.
        /// </summary>
        [Test]
        public void UserId_WhenNotSet_IsNull()
        {
            Assert.That(_identityManager.UserId, Is.Null,
                "UserId should be null before SetUserId is called");
        }
    }
}
